# -*- coding: utf-8 -*-
"""ProyectoIA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15y5HH97SKrRQ53mcHKiLGwldVtfXIGlx

PROYECTO DEL CURSO INTELIGENCIA ARTIFICIAL
"""

#Importamos las librerias que necesitamos
import math
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn

from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

from google.colab import drive
drive.mount('/content/drive')

#Damos permiso para usar archivos de nuestro Drive

df=pd.read_csv('/content/drive/MyDrive/anime.csv')
df.shape
#Cargamos el data set a usar y vemos sus dimensiones

pd.set_option('display.max_columns',35)
#definimos las columnas para mostra por pantalla

df.head() 
#vemos los encabezados antes definidos

df = df.replace('Unknown', float(0))
#hacemos una limpieza de datos reemplazndo string por numeor flotante cero para evitar error con el algoritmo

df.head(2)

df=df.drop(['MAL_ID', 'Name', 'Genres', 'English name', 'Japanese name',
       'Type', 'Aired', 'Premiered', 'Producers', 'Licensors',
       'Studios', 'Source', 'Duration', 'Rating', 'Ranked', 'Score-10', 'Score-9', 'Score-8', 'Score-7', 'Score-6',
       'Score-5', 'Score-4', 'Score-3', 'Score-2', 'Score-1'],axis=1)

#filtramos solo las variables a usar

df.head()